---
- name: Deploy a job to Nomad cluster
  hosts: localhost

  tasks:
    - name: Pull git repo
      git:
        dest: /tmp/homelab-nomad
        repo: https://github.com/qjvtenkroode/homelab-nomad.git
        version: main

    - name: Deploy jobs - {{ deploy_job }}
      community.general.nomad_job:
        content: "{{ lookup('ansible.builtin.file', '/tmp/homelab-nomad/{{ item }}.nomad') }}"
        content_format: hcl
        host: "{{ nomad_leader }}"
        state: present
        use_ssl: false
      with_items: "{{ deploy_job }}"
