---
- name: Create custom fact directory
  file:
    path: /etc/ansible/facts.d
    state: directory

- name: Install custom fact script
  register: custom_fact_installed
  copy:
    src: files/homelab.fact
    dest: /etc/ansible/facts.d/homelab.fact
    mode: 0755

- name: Re-run setup to use custom facts
  setup: ~
  when: custom_fact_installed.changed == true

- name: Print custom facts
  debug:
    msg: "{{ ansible_local.homelab }}"

- name: Install helper packages - unzip
  apt:
    name: unzip
    state: present

- name: Install helper packages - tar
  apt:
    name: tar
    state: present

- name: Install helper packages - nfs-common
  apt:
    name: nfs-common
    state: present

- name: Install packages - python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install python module - python-consul
  pip:
    name: python-consul
