version: '3.8'

services:
  registry:
    deploy:
      endpoint_mode: vip
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    image: registry:2.8.3
    ports:
      - 5000:5000
    volumes:
      - registry_data:/var/lib/registry

volumes:
  registry_data:
    driver_opts:
      type: "nfs"
      o: "addr=truenas.qkroode.nl,nolock,soft,rw"
      device: ":/mnt/homelab/csi/vols/registry"
