---
- name: Install Docker
  import_tasks: docker.yml

- name: Install Hashicorp stack - Nomad
  block:
    - name: Download Nomad - {{ nomad_version }}
      get_url:
        url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip"
        dest: "{{ download_dir }}/nomad-{{ nomad_version }}.zip"
        checksum: "{{ nomad_checksum }}" 

    - name: Expand Nomad and place in {{ binary_dir }}
      unarchive:
        src: "{{ download_dir }}/nomad-{{ nomad_version }}.zip"
        dest: "{{ binary_dir }}"
        remote_src: true
      notify:
        - Restart nomad

    - name: Cleanup
      file:
        path: "{{ download_dir }}/nomad-{{ nomad_version }}.zip"
        state: absent
  when: ansible_local.homelab.nomad_version != nomad_version

- name: Configure Hashicorp stack - Nomad
  block:
    - name: Create config directory
      file:
        path: /etc/nomad.d
        state: directory
    
    - name: Nomad common config
      template:
        src: templates/common.j2
        dest: /etc/nomad.d/common.hcl
      notify:
        - Restart nomad

    - name: Nomad client config
      template:
        src: templates/client.j2
        dest: /etc/nomad.d/client.hcl
      notify:
        - Restart nomad

    - name: Nomad server config
      template:
        src: templates/server.j2
        dest: /etc/nomad.d/server.hcl
      notify:
        - Restart nomad
      when: nomad_type == "server"

    - name: Nomad host volumes
      template:
        src: templates/host_volumes.j2
        dest: /etc/nomad.d/host_volumes.hcl
      notify:
        - Restart nomad
      when: dedicated_photoprism is defined

    - name: Nomad setup systemd for server
      copy:
        src: nomad-server.systemd
        dest: /etc/systemd/system/nomad.service
      when: nomad_type == "server"
      notify:
        - Restart nomad

    - name: Nomad setup systemd for client
      copy:
        src: nomad-client.systemd
        dest: /etc/systemd/system/nomad.service
      when: nomad_type == "client"
      notify:
        - Restart nomad

    - name: Setup Photoprism dedicated node
      block:
        - name: NFS - Create directories - orginals 
          file:
            path: /mnt/originals
            state: directory

        - name: Create directories - photoprism 
          file:
            path: /opt/photoprism
            state: directory

        - name: NFS - Mount - photoprism - original media
          ansible.posix.mount:
            src: truenas.qkroode.nl:/mnt/NAS/photo
            path: /mnt/originals
            fstype: nfs
            opts: rw,sync
            state: mounted
      when: dedicated_photoprism is defined
    
    - name: Nomad systemd enabled and started
      systemd:
        name: nomad
        enabled: true
        state: started
