---
- name: Create custom fact directory
  file:
    path: /etc/ansible/facts.d
    state: directory

- name: Install custom fact script
  register: custom_fact_installed
  copy:
    src: files/homelab.fact
    dest: /etc/ansible/facts.d/homelab.fact
    mode: 0755

- name: Re-run setup to use custom facts
  setup: ~
  when: custom_fact_installed.changed == true

- name: Print custom facts
  debug:
    msg: "{{ ansible_local.homelab }}"

- name: Install helper packages - unzip
  apt:
    name: unzip
    state: present

- name: Install helper packages - tar
  apt:
    name: tar
    state: present

- name: Install helper packages - nfs-utils
  apt:
    name: nfs-utils
    state: present

- name: Install packages - podman
  apt:
    name: podman
    state: present

- name: Install python module - python-consul
  pip:
    name: python-consul

- name: Podman add private insecure repositories
  copy:
    src: private-testing.conf
    dest: /etc/containers/registries.conf.d/private.conf
  when: nomad_datacenter == "testing"

- name: Podman add private insecure repositories
  copy:
    src: private.conf
    dest: /etc/containers/registries.conf.d/private.conf
  when: nomad_datacenter == "homelab"

- name: Podman systemd enabled and started
  systemd:
    name: podman
    enabled: true
    state: started
