version: '3.8'

services:
  bookkeeper:
    deploy:
      endpoint_mode: vip
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    image: minions.qkroode.nl:5000/homelab/hivemind-bookkeeper:latest
    ports:
      - 8005:8000
    logging:
      options:
        splunk-sourcetype: hivemind:bookkeeper
  shelly:
    deploy:
      endpoint_mode: vip
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    image: minions.qkroode.nl:5000/homelab/hivemind-shelly:latest
    ports:
      - 8006:8000
    logging:
      options:
        splunk-sourcetype: hivemind:shelly
